### PR TITLE
GUI for LaMEM using Dash.jl

### PR DESCRIPTION
**Pull request by jamisonassuncao**
GUI developed during the Julia Hackathon v4 using the Dash.jl and Dash Bootstrap Components.

### CODE REVIEW

**Comment by boriskaus** [comment]
Can you update the readme file as well to give a quick overview of the new apps?

**Comment by albert-de-montserrat** [comment]
Looks cool guys! I've been testing it out and seems to work fine :) Some minor comments/ideas:

1. Looks like you need to do `cd("path/to/GUI/folder")` to run the scripts (e.g. `RisingSphere.jl`). Could it be possible to run it from the main folder? I.e. opening the main folder in VSC and run the GUI by clicking on the run button. I also see that it changes what directory I am in after I click on run.

2. Maybe you could fix the x and y lims of the plots to match the heatmaps
Screenshot 2023-09-26 at 14 12 29.

3. Is it possible to update the plot instead of having to re-run the model if I change stuff in the `Plotting Parameters` box?

4. I guess you are aware, only `RisingSphere.jl` seems to be working.

5. To make it a bit more flexible, could the user define a given field by being able to pass an anonymous function? Let's say I would want to perturb density, I could just pass it as `(x, y) -> -sin(2 * y) * cos(3 * π * x)`

**Comment by boriskaus** [comment]
> 1. Looks like you need to do `cd("path/to/GUI/folder")` to run the scripts (e.g. `RisingSphere.jl`). Could it be possible to run it from the main folder? I.e. opening the main folder in VSC and run the GUI by clicking on the run button. I also see that it changes what directory I am in after I click on run.

This is indeed a good idea; if we have this as a registered package users should just be able to just do:
```Julia
julia> using InteractiveGeodynamics
julia> RisingSphere()
```
We did that in [GeoDataPicker](https://github.com/JuliaGeodynamics/GeoDataPicker.jl). It does require a bit of rewriting, though.

> 2. Maybe you could fix the x and y lims of the plots to match the heatmaps
>    Screenshot 2023-09-26 at 14 12 29.

would be nice to change

> 3. Is it possible to update the plot instead of having to re-run the model if I change stuff in the `Plotting Parameters` box?

I think that possibility is there already; simply push `Play/Pause` again

> 4. I guess you are aware, only `RisingSphere.jl` seems to be working.

to be changed.

> 5. To make it a bit more flexible, could the user define a given field by being able to pass an anonymous function? Let's say 

I would want to perturb density, I could just pass it as `(x, y) -> -sin(2 * y) * cos(3 * π * x)`
That will not work as this is not build into LaMEM, which is phase-based. The only field that can be changed in this way is temperature

**Comment by jamisonassuncao** [comment]
Regarding the directory issue: yes, the active directory will be modified to accommodate this in the future. However, up to this point, it has proven somewhat challenging.

Regarding the plotting: we're currently addressing the plotting area and axis limits, as we've encountered difficulty in achieving this without compromising the aspect ratio.

All other scripts like NAME_Dash.jl (Convection_Dash.jl and RTI_Dash.jl) should run smoothly without any problems--allegedly.

**Pull request merged**
